baseURL = "https://Chesszyh.github.io/"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

staticDir = ["static"]  

[module]
[module.hugoVersion]
min = "0.100.0"
[languages]
[languages.en]
title = "{CodeTrace} - Discover Issues, Share Solutions."
languageCode = "en-us"
LanguageName = "🇺🇸EN"
contentDir = "content/en"
weight = 1
[[languages.en.menus.main]]
name = 'Home'
pageRef = '/'
weight = 1
[[languages.en.menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 2
[[languages.en.menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 3
[[languages.en.menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 4
[[languages.en.menus.main]]
name = 'Play Chess'
pageRef = '/chess'
weight = 5


[languages.zh]
title = "CodeTrace"
languageCode = "zh-cn"
LanguageName = "🇨🇳CN"
contentDir = "content/zh"
weight = 2
[[languages.zh.menus.main]]
name = '首页'
pageRef = '/'
weight = 1
[[languages.zh.menus.main]]
name = '文章分类'
pageRef = '/categories'
weight = 2
[[languages.zh.menus.main]]
name = '标签'
pageRef = '/tags'
weight = 3
[[languages.zh.menus.main]]
name = '联系我'
pageRef = '/contact'
weight = 4
[[languages.zh.menus.main]]
name = '和我下棋'
pageRef = '/chess'
weight = 5

[params]
[params.google]
google_ad_client = ""
ga4 = "G-KRJ7MGKP6J"
[params.bannershowcase]
categories = ["AI"]
limit = 2
[params.email]
contact = "chesszyh987@gmail.com"
[params.ignore]
categories = ["privacy", "terms", "archives", "cookie"]
[params.license]
copyright = ""
[params.share]
sharethis = ""

[outputs]
home = ["HTML", "JSON"]
